### ISSUE TITLE
Minimum Viable Version of Game

### ISSUE THREAD

**Issue by skatt621** [cps209-team3/joust#1]
Here's what I have about what we need to do to turn SOMETHING in (includes what's in the 80% version of the project specs, of course).

• Defined, non-random levels
• No networking; single player with only computer opponents
• Character class with two sub-classes: one for the character and the other a parent class with    sub-class(es) for AI characters
• The game is based off collision so we need to add this for every character class.
• No gravity; free roaming

Is there anything on this list that we need to add?

**Comment by jacobrfr** [comment]
Gravity is pretty much essential to the game since there is no down key.

**Comment by jacobrfr** [comment]
This is defined in the proposal, and will be further specified in the game specification.
