### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by jacobrfr** [cps209-team3/joust#11]

**Comment by jacobrfr** [comment]
I think the Save and Load methods are just supposed to call the Serialize and Deserialize methods of each object. I don't think Load needs a user parameter since we don't have to implement load/save for multiplayer, so we can store their saves locally. There should be a list of saves that they can scroll through. When they select one, the filename related to that save should be sent to GameController's Load and that should be all it needs to find the save. If you're going to store all the saves in the same file, then you won't need a filename, just some parameter like the name of the save to find it. Not sure if I made myself clear, but that's my understanding of it.

**Comment by jefti558** [comment]
So I'm going to sort the saves by date/time. Not sure if we want the user to have the ability to name saves.
