### ISSUE TITLE
Intro to genre and game concept overview

### ISSUE THREAD

**Issue by jacobrfr** [cps209-team3/joust#2]

**Comment by jacobrfr** [comment]
The enemies do not ride ostriches, they ride buzzards or pterodactyls. The second sentence of the second paragraph doesn't agree with the game play since there is an unlimited number of stages, enemies don't get faster, and you won't necessarily have less lives each stage. We don't need the mention of real world figures being coincidental either. The enemies don't drop pills, they drop eggs.

**Comment by skatt621** [comment]
Will do changes todsy.
________________________________

**Comment by jacobrfr** [comment]
Looks good to me. Let me know what yall think. @jefti558 @ccock237

**Comment by jefti558** [comment]
I don't think "traversing" is specific enough, I would mention eliminating enemies and or surviving as these are more defined as the goal of the game.

**Comment by jacobrfr** [comment]
Done.
