### ISSUE TITLE
Bullet list for game features

### ISSUE THREAD

**Issue by jacobrfr** [cps209-team3/joust#4]

**Comment by jacobrfr** [comment]
Feel free to add any features you think of that we may implement.

**Comment by jacobrfr** [comment]
There is no B-level and gravity is part of the core game logic. I already made the changes and added a few features to the list. I'm good with this list in its current state. Please leave a thumbs up if you're good with it @jefti558 @ccock237 @skatt621

**Comment by jefti558** [comment]
Are you sure there is no B-level? According to the proposal requirements page there is a B-level. http://cs.bju.edu/cps/courses/cps209/project/Proposal.html

**Comment by skatt621** [comment]
yeah. it says b-level is the network or multiplayer. these are the examples he gave for a level (i guess)

Multiple levels (complete one level to progress to the next)
Game level designer application (if your game has levels)
Easter eggs

he was vague and said the possibilities for extra features includes these

**Comment by skatt621** [comment]
sorry, closed this by accident.
i suggest we make the bonuses the a level and talk about extra features in lab tomorrow.

**Comment by jefti558** [comment]
I'm putting live-action as B-Level since it'll be in the base single player version of the game.

**Comment by jacobrfr** [comment]
I moved cross platform and level designer to bonus since that's where it is in the sample. We can change this if needed.

**Comment by jacobrfr** [comment]
Done.
