### ISSUE TITLE
5 minute presentation

### ISSUE THREAD

**Issue by jacobrfr** [cps209-team3/joust#5]

**Comment by skatt621** [comment]
i guess im doin this. five minutes should be easy. ill start with reading the overview verbatim. then i will go into gameplay (how to play, points, respawning, etc.) and then explain the feature list (probably just hitting the highlights).

**Comment by jacobrfr** [comment]
We can ask Dr. Schaub about the presentation in class tomorrow. I think a PowerPoint would be a good idea.

**Comment by jacobrfr** [comment]
Done.
