### ISSUE TITLE
Object model

### ISSUE THREAD

**Issue by jacobrfr** [cps209-team3/joust#8]

**Comment by jacobrfr** [comment]
Created object-model branch for this issue. Check it out and let me know what you think. I think JD was right that the World singleton shouldn't have a setter but i'm not sure if we should be using a singleton at all due to difficult unit testing. Anyone remember what Dr. Schaub recommended in his last lecture about singletons?

**Comment by jefti558** [comment]
In order to make scoring easier, consider putting either a "reward" instance variable or method into the enemy class. This instance variable/method would either return a score (int) value or directly add to the player's total score. This way we don't have to test for the type of enemy when the user gains points.

**Comment by jacobrfr** [comment]
I added a Value (property since fields can't be abstract). I added it to the Entity class instead of the Enemy class since Ostriches are worth 750 points in multiplayer mode.

**Comment by jacobrfr** [comment]
I also added a score instance variable to the Ostrich class and made WorldObject, Entity, and Enemy abstract classes

**Comment by jefti558** [comment]
Could you add the GameController.cs class to the model.

**Comment by jacobrfr** [comment]
Correct.

**Comment by jefti558** [comment]
Created another branch containing a "PlayerStats.cs" class. This is needed to keep track of player statistics. Feel free to change names to your liking and/or add more statistics that can be tracked.

**Comment by jacobrfr** [comment]
Why do we need a new class for this? Can't these just be instance variables in the Ostrich class? I also feel like the stage number should be in the World class instead of a player related class.

**Comment by jefti558** [comment]
Simply to keep track of the statistics for saving and loading. The world class should still have stage numbers in it but the PlayerStats class will take from the world class.

**Comment by jacobrfr** [comment]
Right but shouldn't those statistics be stored in the Ostrich class? Then when you save you just loop through a list of worldobjects stored in world. The extra class just seems extraneous since we will already have to loop through all the worldobjects anyways since we will need to store enemy positions and such. We could still loop through the worldobjects with this approach but we would need to store a PlayerStats object in each Ostrich and define an Ostrich method to get the stats out of the class when we could just store the stats in Ostrich itself.

**Comment by jefti558** [comment]
For save/load the idea is to save at a certain stage number and when the player loads he will start at that level. The class is supposed to give a simple organized way of storing statistics to a game file that will hold the statistics of every player based on his username. 
The functionality of the PlayerStats class could be put into each ostrich. I just thought this would be simpler since all the logic would be contained in an object in the ostrich/player class.

**Comment by jacobrfr** [comment]
If you look at the save/load description here: http://cs.bju.edu/cps/courses/cps209/project/ProjectOverview.html

schaub says we have to save it in progress, not just load the current level.

Also, in the Serialization section here:
http://cs.bju.edu/cps/courses/cps209/project/ProjectDesign.html

schaub says we should define a load and save method for the world, and then each object should have a serialize and deserialize method to save its own state and retrieve its own state from the save file.

**Comment by jefti558** [comment]
Okay, I'll define serialize/de-serialize methods for each world object. I missed the fact that we had to save in-level progress. And I'll add the PlayerStats instances to the ostrich(player) class. I'll have it done before 12 tonight.

**Comment by jefti558** [comment]
So both the "Platform" and "Respawn" classes need to have their own implementation of Iserialization. I'm not too sure about how this should be implemented since "Respawn" is inheriting from "Platform".

**Comment by jacobrfr** [comment]
I renamed your interface to ISerializable (based on common interface naming) and moved it to its own file (ISerializable.cs). Your Deserialize method should only have one argument, a single string that you split into the parts needed. This way you can just make Serialize and Deserialize abstract methods on WorldObject and override them for each Subclass. Visual Studio is complaining because you have multiple sets of parameters across different classes. You need to define the parameter(s) to use in ISerializable and use the same parameters for each implementation.

**Comment by jefti558** [comment]
From my understanding of Interfaces there is no need to make it an abstract class in WorldObject.

**Comment by jefti558** [comment]
Could you elaborate on the problem visual studio is having. I'm not sure what parameters you are referring to.

**Comment by jefti558** [comment]
I've changed all the Deserialize methods to take one parameter.

**Comment by jacobrfr** [comment]
The Interface itself isn't what I was referring to. You define the methods you want to implement (Serialize and Deserialize) in the interface. Then, Serialize and Deserialize should be abstract **methods** in WorldObject.cs (and probably regular methods in World.cs as well, because there will be some info in there that we will need to save/load). Then you go and override the Serialize and Deserialize methods in each subclass of WorldObject. This way you can loop through the list of WorldObjects stored in World and call Serialize or Deserialize on each one, and polymorphism will call that subclass's implementation of the method.

**Comment by jacobrfr** [comment]
Don't forget to have the Interface's Deserialize take one parameter as well. The Deserialize in the ISerializable definition should have the same number of parameters as every implementation of ISerializable, and they should be of the same type as well.

**Comment by jacobrfr** [comment]
Also, could you group similar changes into one branch? It makes it faster to merge the pull requests.

**Comment by jefti558** [comment]
I don’t see why there needs to be abstract methods in the worldobject class. From my understanding, defining abstract methods and defining an interface are two different ways of doing something similar. And since Dr. Schaub wants an Interface there seems to be no need for the abstract method in the parent class since the Interface is requiring the methods be defined in all objects that need to be saved. 

If you're asking for the interface to be implemented by only the Worldobject class and then have each class override the methods in that then I don't think that is adhering to the specifications Dr. Schaub gave for serialization. http://cs.bju.edu/cps/courses/cps209/project/ProjectDesign.html

**Comment by jacobrfr** [comment]
The WorldObject class will not really implement the interface, it will define abstract serialize and deserialize methods, the implementation is in each subclass. This is hardly different from what you have now, but it guarantees that all WorldObjects will implement ISerializable. I don't see how this would violate the instructions, but the decision is yours.

**Comment by jefti558** [comment]
Okay, I understand what you're suggesting. According to the instructions: "All objects that load/save themselves should **implement an interface** that you design with methods to serialize and deserialize the object state." This make it seem like Schaub wants each object to use the interface itself. Your way basically follows this but I'm going to keep it the way it is now to be safe.

**Comment by jacobrfr** [comment]
Okay. I think he would be fine with this so I'll ask in class today.

**Comment by jefti558** [comment]
The only problem with having **every** world object implement the interface is that some of the objects don't need to be saved. (entity, enemy) so this would make unnecessary code necessary.

**Comment by jacobrfr** [comment]
Those are abstract classes, so they cannot be instantiated.

**Comment by jacobrfr** [comment]
Theose classes would inherit the abstract method from WorldObject, so we wouldn't need to add any new code.

**Comment by jefti558** [comment]
I see. Well, in that case your way does seem better. Just ask in class and I'll change it afterwords if it's fine.

**Comment by jacobrfr** [comment]
Done.
